name: Upload Release Asset

on:
  push:
    tags:
    - 'v*-rc.*' # "e.g. v0.4"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        # We need to do this because of how github cache works
        # I am not sure we can move the cache file, so if we do not do this
        # make update breaks because the cached compiler is there where the submodules
        # are meant to go.
      # - name: Submodules
      #   run: |
      #     git submodule update --init --recursive
          
      # - name: Cache nim
      #   uses: actions/cache@v1
      #   with:
      #     path: vendor/nimbus-build-system/vendor/Nim/bin
      #     key: ${{ runner.os }}-${{ matrix.env.NPROC }}-nim-${{ hashFiles('.gitmodules') }}

      - name: build artifacts
        run: |
          mkdir -p build/
          echo "echo wakunode2" > ./build/wakunode2
          chmod +x ./build/wakunode2
          tar -cvzf nim-waku.tar.gz ./build/

#make -j2 NIMFLAGS="--parallelBuild:${NPROC}" QUICK_AND_DIRTY_COMPILER=1 CI=false wakunode2
            
      
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wakunode2
          path: nim-waku.tar.gz

  create-release-candidate:
    runs-on: ubuntu-latest
    needs: [ build-and-publish ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - name: download artifacts
        uses: actions/download-artifact@v2
      - name: generate release notes
        run: |
          git status
          docker run \
              -t \
              --rm \
              -v ${PWD}:/opt/sv4git/repo:z \
              -u $(id -u) \
              docker.io/wakuorg/sv4git:latest \
                release-notes -t ${{github.ref_name}} |\
                sed -E 's@#([0-9]+)@[#\1](https://github.com/waku-org/nwaku/issues/\1)@g' > release_notes.md

          cat release_notes.md
          ls -la
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release view ${{github.ref_name}} &>/dev/null && gh release delete -y ${{github.ref_name}}
          gh release create ${{github.ref_name}} --prerelease --verify-tag \
            --title '${{github.ref_name}}' --notes-file release_notes.md \
            wakunode2/*
        
      
